steps:
  # -----------------------------
  # 1. Read version from pyproject.toml.....
  # -----------------------------
  - name: python:3.11
    id: read-image-version
    entrypoint: bash
    args:
      - "-c"
      - |
        pip install pyyaml
        _IMG=$(python3 - <<'EOF'
        import yaml
        with open("manifest.yaml") as f:
            data = yaml.safe_load(f)
            version = data["image"]["version"]
            print(version)
        EOF
        )
        echo "IMAGE=${_IMG}" > /workspace/image.env
        echo "IMAGE=${_IMG}"
        
  # -----------------------------
  # 2. Build Docker image using version
  # -----------------------------
  - name: gcr.io/cloud-builders/docker
    id: "build-image"
    entrypoint: bash
    args:
      - "-c"
      - |
        source /workspace/version.env
        docker build -t europe-west2-docker.pkg.dev/$PROJECT_ID/docker-wif-demo/coldstore:1 .

  # -----------------------------
  # 3. Push image
  # -----------------------------
  - name: gcr.io/cloud-builders/docker
    id: "push-image"
    entrypoint: bash
    args:
      - "-c"
      - |
        source /workspace/version.env
        docker push europe-west2-docker.pkg.dev/$PROJECT_ID/docker-wif-demo/coldstore:1

options:
  logging: CLOUD_LOGGING_ONLY
  automapSubstitutions: true
  env:
    - _VERSION="1.0.0"  # Default version if pyproject.toml is not found

images:
  - europe-west2-docker.pkg.dev/$PROJECT_ID/docker-wif-demo/coldstore:1
